# if new survey, provide survey params
new_survey: False
survey_type: 'test' # 'incremental' #  # 'test' # 'full', 'incremental', 'test_max_page'
location: 'warsaw'
max_page_num: 1 #243 # limit page num for testing purposes

# if you want to continue survey, choose which one
survey_to_continue: test_2023-11-13_warsaw_5 # incremental_2023-11-09_warsaw_1 # incremental_2023-11-08_warsaw_1 #base_full_survey # incremental_2023-11-08_warsaw_1

# modules to run
module_scraping: True
module_data_cleaning: False
excluded_cleaners: [] # [] ['NumericDataCleaner', 'CategoricalDataCleaner', 'LabelDataCleaner']
module_lat_lon_coding: False
module_extract_geo_features: False
module_make_dummy_geo_features: False

# needed only the first time
module_get_shp_files: False

sqlite_db: "data/real_estate.db"

# scraping
# WARNING: can end up in 403 responses if used on too many links
use_async_scraping: False #True

base_link: "https://www.otodom.pl/pl/wyniki/sprzedaz/mieszkanie/wiele-lokalizacji?locations=%5Bmazowieckie%2Cmazowieckie%2Fwarszawa%2Fwarszawa%2Fwarszawa%5D&viewType=listing&limit=72&page={}"

headers: {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}

# lat lon geoencoding
nominatim_timeout: 10
nominatim_user_agent: "kubaokrzesa"

# shpefiles
shp_files_directory_name: "shp_files"
shp_urls: ["https://www.gis-support.pl/downloads/2022/gminy.zip",
  "https://www.gis-support.pl/downloads/2022/powiaty.zip",
"https://www.gis-support.pl/downloads/2022/jednostki_ewidencyjne.zip"]